[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/why-iulink"
  to = "/why-linkvec"
  status = 301

[build.processing.html]
  pretty_urls = false
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
